# frozen_string_literal: true

require "fileutils"

ROOT = File.expand_path("..", __dir__)
OUTPUT = File.join(ROOT, "Sources", "KpqCCore", "Generated")

PQC_FIPS202_SYMBOLS = %w[
  sha3_256 sha3_256_inc_absorb sha3_256_inc_ctx_clone
  sha3_256_inc_ctx_release sha3_256_inc_finalize sha3_256_inc_init
  sha3_384 sha3_384_inc_absorb sha3_384_inc_ctx_clone
  sha3_384_inc_ctx_release sha3_384_inc_finalize sha3_384_inc_init
  sha3_512 sha3_512_inc_absorb sha3_512_inc_ctx_clone
  sha3_512_inc_ctx_release sha3_512_inc_finalize sha3_512_inc_init
  shake128 shake128_absorb shake128_ctx_clone shake128_ctx_release
  shake128_inc_absorb shake128_inc_ctx_clone shake128_inc_ctx_release
  shake128_inc_finalize shake128_inc_init shake128_inc_squeeze
  shake128_squeezeblocks shake256 shake256_absorb shake256_ctx_clone
  shake256_ctx_release shake256_inc_absorb shake256_inc_ctx_clone
  shake256_inc_ctx_release shake256_inc_finalize shake256_inc_init
  shake256_inc_squeeze shake256_squeezeblocks
].freeze

COMPACT_FIPS202_SYMBOLS = %w[
  KeccakF_RoundConstants sha3_256 sha3_512 shake128 shake128_absorb
  shake128_absorb_once shake128_finalize shake128_init shake128_squeeze
  shake128_squeezeblocks shake256 shake256_absorb shake256_absorb_once
  shake256_finalize shake256_init shake256_squeeze shake256_squeezeblocks
].freeze

NTRUPLUS_SYMBOLS = %w[
  baseinv basemul basemul_add crypto_kem_dec crypto_kem_enc
  crypto_kem_keypair hash_f hash_g hash_h invntt ntt poly_baseinv
  poly_basemul poly_basemul_add poly_cbd1 poly_crepmod3 poly_frombytes
  poly_invntt poly_ntt poly_sotp_decode poly_sotp_encode poly_sub
  poly_tobytes poly_triple zetas
].freeze

HAETAE_SYMBOLS = %w[
  brv8 fix_round hammingWeight_8 polyfixfix_sub sample_gauss
  shake128_stream_init shake256_absorb_thrice shake256_absorb_twice
  shake256_stream_init start_cube start_times_threehalves
].freeze

SMAUGT_SYMBOLS = %w[flipabs shake256_absorb_twice_squeeze].freeze

HAETAE_SOURCES = %w[
  decompose encoding fft fixpoint ntt packing poly polyfix polymat polyvec
  reduce sampler sign fips202 symmetric-shake
].map { |name| "vendor/HAETAE/src/#{name}.c" }.freeze

SMAUGT_SOURCES = %w[
  cbd ciphertext dg hash hwt indcpa kem key pack packring poly toomcook verify
  fips202
].map { |name| "vendor/SMAUG-T/src/#{name}.c" }.freeze

def algorithm(name:, wrapper:, sources:, includes:, defines: {}, renames: [])
  {
    name: name,
    wrapper: wrapper,
    sources: sources,
    includes: includes,
    defines: defines,
    renames: renames
  }
end

algorithms = []

%w[128f 128s 192f 192s 256f 256s].each do |parameter|
  root = "vendor/AIMer"
  name = "aimer#{parameter}"
  algorithms << algorithm(
    name: name,
    wrapper: "signature.c",
    sources: %W[
      #{root}/aim2.c #{root}/hash.c #{root}/sign.c #{root}/tree.c
      #{root}/field#{parameter[0, 3]}.c #{root}/common/fips202.c
    ],
    includes: [root, "#{root}/common"],
    defines: { "PARAMS" => parameter, "KPQC_AIMER" => "1" },
    renames: %w[
      crypto_sign_keypair_internal crypto_sign_signature_internal
      crypto_sign_verify_internal
    ] + PQC_FIPS202_SYMBOLS
  )
end

{ "haetae2" => 0, "haetae3" => 1, "haetae5" => 2 }.each do |name, mode|
  algorithms << algorithm(
    name: name,
    wrapper: "signature.c",
    sources: HAETAE_SOURCES,
    includes: ["vendor/HAETAE/include"],
    defines: { "HAETAE_CONFIG_MODE" => mode.to_s },
    renames: COMPACT_FIPS202_SYMBOLS + HAETAE_SYMBOLS
  )
end

%w[768 864 1152].each do |parameter|
  root = "vendor/NTRUplus/NTRU+#{parameter}"
  name = "ntruplus#{parameter}"
  algorithms << algorithm(
    name: name,
    wrapper: "kem_wrapper.c",
    sources: %W[
      #{root}/kem.c #{root}/ntt.c #{root}/poly.c #{root}/symmetric.c
      #{root}/fips202/fips202.c
    ],
    includes: [root, "#{root}/fips202"],
    renames: NTRUPLUS_SYMBOLS + PQC_FIPS202_SYMBOLS
  )
end

{ "smaugt128" => 0, "smaugt192" => 1, "smaugt256" => 2, "timer" => 3 }.each do |name, mode|
  algorithms << algorithm(
    name: name,
    wrapper: "kem_wrapper.c",
    sources: SMAUGT_SOURCES,
    includes: ["vendor/SMAUG-T/include"],
    defines: { "SMAUGT_CONFIG_MODE" => mode.to_s },
    renames: COMPACT_FIPS202_SYMBOLS + SMAUGT_SYMBOLS
  )
end

FileUtils.rm_rf(OUTPUT)

algorithms.each do |entry|
  directory = File.join(OUTPUT, entry[:name])
  FileUtils.mkdir_p(directory)

  guard = "KPQC_GENERATED_#{entry[:name].upcase}_CONFIG_H"
  definitions = {
    "KPQC_PREFIX" => "kpqc_#{entry[:name]}_",
    "randombytes" => "kpqc_#{entry[:name]}_randombytes"
  }.merge(entry[:defines])
  entry[:renames].each do |symbol|
    definitions[symbol] = "kpqc_#{entry[:name]}_#{symbol}"
  end

  config = ["/* Generated by scripts/generate_native_sources.rb. */",
            "#ifndef #{guard}", "#define #{guard}"]
  definitions.each { |key, value| config << "#define #{key} #{value}" }
  config << "#endif"
  File.write(File.join(directory, "config.h"), config.join("\n") + "\n")

  units = entry[:sources] + ["native/csrc/#{entry[:wrapper]}"]
  units.each_with_index do |source, index|
    basename = File.basename(source, ".c").tr("-+", "__")
    filename = format("%02d_%s.c", index, basename)
    content = File.read(File.join(ROOT, source)).gsub(
      /^(\s*#\s*include\s*)"([^"]+)"/
    ) do
      prefix = Regexp.last_match(1)
      header = Regexp.last_match(2)
      search = [File.dirname(source), *entry[:includes]]
      resolved = search
                 .map { |directory_name| File.join(directory_name, header) }
                 .find { |candidate| File.file?(File.join(ROOT, candidate)) }
      resolved ? "#{prefix}\"#{resolved}\"" : Regexp.last_match(0)
    end
    File.write(
      File.join(directory, filename),
      "/* Generated by scripts/generate_native_sources.rb. */\n" \
      "#include \"config.h\"\n" \
      "#line 1 \"#{source}\"\n" \
      "#{content}"
    )
  end

  File.write(
    File.join(directory, format("%02d_randombytes.c", units.length)),
    "/* Generated by scripts/generate_native_sources.rb. */\n" \
    "#include \"config.h\"\n" \
    "#if defined(KPQC_TEST_ENTROPY)\n" \
    "#include \"native/csrc/randombytes_test.c\"\n" \
    "#else\n" \
    "#include \"native/csrc/randombytes.c\"\n" \
    "#endif\n"
  )
end

warn "generated native sources for #{algorithms.length} parameter sets"
